### PR TITLE
[WIP] Accommodate upstream V8 6.7 API changes

### PR DESCRIPTION
**Pull request by ignisf**
- [x] Decide if `Isolate#idle_notification` should be removed
- [x] Debug why `MiniRacerTest#test_isolate_can_be_notified_of_idle_time` fails and if the test itself makes sense
- [ ] Wait for a stable libv8 6.7 release (https://github.com/cowboyd/libv8/pull/258)

### CODE REVIEW

**Comment by SamSaffron** [comment]
@wk8 what is your call here, I am merging this in for now and correcting test / removing interface

**Comment by SamSaffron** [comment]
@wk8  what is your call here?

**Comment by SamSaffron** [comment]
OK I fixed the idle_notification stuff, but am still getting segfaults... @ignisf  any chance you can do a v8 release with symbols?

**Comment by ignisf** [comment]
sure

**Comment by ignisf** [comment]
https://github.com/cowboyd/libv8/releases/download/v6.7.288.46.1beta0/debug-libv8-6.7.288.46.1beta0-x86_64-linux.gem

It seems it has some debugging checks enabled which cause the test suite to fail with SIGABRT, which actually might be helpful. :)

Just uninstall the nondebug version, download the debug binary, install it with gem install ./debug-*, and recompile mini_racer

**Comment by ignisf** [comment]
I commented out the tests that were failing due to debug checks and ran `while (true); rake test; done`.

The `test_undef_mem` failed periodically. Here's a backtrace: https://gist.githubusercontent.com/ignisf/6fb047e9582aa9b3f257502d71ddd619/raw/80c772634461550cde3690c9e8c96950ae7b9008/gistfile1.txt

**Pull request merged**
