### PR TITLE
Update and expand the Travis configuration

### PR DESCRIPTION
**Pull request by ignisf**
Make Travis use Ubuntu Trusty for Linux builds and introduce an OS X
build.

### CODE REVIEW

**Comment by SamSaffron** [comment]
ouch 

```
/Users/travis/build/discourse/mini_racer/lib/mini_racer.rb:2:in `require': dlopen(/Users/travis/build/discourse/mini_racer/lib/mini_racer_extension.bundle, 9): Symbol not found: __ZNSoD0Ev (LoadError) 
```

:(

I can still pull this in, no probs

**Comment by ignisf** [comment]
Not yet please :)

**Comment by SamSaffron** [comment]
Ahh ... I fixed this in the past ... that was the stdlib thing ... 

```
_std::basic_ostream<char, std::char_traits<char> >::~basic_ostream() 
```

**Comment by ignisf** [comment]
Ah, OK :)

**Comment by SamSaffron** [comment]
oops ... pulled it ... a sec to late

**Comment by SamSaffron** [comment]
```
$LDFLAGS.insert 0, " -stdlib=libstdc++ " if RUBY_PLATFORM =~ /darwin/
```

This should fix it

**Comment by SamSaffron** [comment]
probably belongs in libv8 though ...

**Comment by ignisf** [comment]
Just append `      osx_image: xcode7.3` to the build matrix

**Comment by SamSaffron** [comment]
k done

**Pull request merged**
