### PR TITLE
timeout failcase test case

### PR DESCRIPTION
**Pull request by seanmakesgames**

### CODE REVIEW

**Comment by SamSaffron** [comment]
Wait, I think I corrected this, is it still the case?

**Comment by seanmakesgames** [comment]
I'll run the test case against latest and take a look.

**Comment by SamSaffron** [comment]
Lets try again with my latest commit :)

**Comment by seanmakesgames** [comment]
Ok. Will do after lunch. :)

**Comment by seanmakesgames** [comment]
@SamSaffron I changed this pr into a passing testcase. :) woo! 
(thanks for the fix; Gonna be running it with my game's test suite w/ upgraded v8, too.)

**Comment by SamSaffron** [comment]
cool!

**Pull request merged**
