### PR TITLE
Introduce compatibility with V8 7.3

### LINKED ISSUE #115: Remove instances of use of functions deprecated in V8 7.3
- [x] Use of non-isolate version of `String::Utf8Value` https://github.com/v8/v8/commit/ce05578aa6606cf662984a968cc99d421cea30d8 (https://github.com/discourse/mini_racer/pull/116)
- [x] Use of non-maybe version of `Message::GetLineNumber` https://github.com/v8/v8/commit/5acf20551217ddce89c20c7c8848ae971eb192c2#diff-3dd7a0f46b1e5c1cc67921449e7180acL1781 (https://github.com/discourse/mini_racer/pull/117)
- [x] Use of non-maybe version of `TryCatch::StackTrace` https://github.com/v8/v8/commit/5acf20551217ddce89c20c7c8848ae971eb192c2#diff-3dd7a0f46b1e5c1cc67921449e7180acL9023 (https://github.com/discourse/mini_racer/pull/118)
- [x] Use of `V8::CreateSnapshotDataBlob` and `V8::WarmUpSnapshotDataBlob` instead of `SnapshotCreator` https://github.com/v8/v8/commit/b3738e658345adabaa958b9f9a94ca01fc87d5e4
- [x] Use of `String::Utf8Length` https://github.com/v8/v8/commit/3dd5c6fe38355b8323597341409b37f931de5a85
- [x] Use of `String::ToObject` https://github.com/v8/v8/commit/c8376b0069ebe16c67acf90c3cda3457ddccba4f
- [x] Use of `Local::ToString()` https://github.com/v8/v8/commit/c8376b0069ebe16c67acf90c3cda3457ddccba4f
- [x] Use of non-maybe version of `Value::Int32Value` https://github.com/v8/v8/commit/c8376b0069ebe16c67acf90c3cda3457ddccba4f
- [x] Use of non-maybe version of `Value::NumberValue` https://github.com/v8/v8/commit/c8376b0069ebe16c67acf90c3cda3457ddccba4f
- [x] Use of non-maybe version of `Date::New` https://github.com/v8/v8/commit/e84b92d7658dee79c34304a67c4fb84c93cd071b

### PR DESCRIPTION
**Pull request by ignisf**
Fixes #115 
Closes #125

### CODE REVIEW

**Comment by ignisf** [comment]
@SamSaffron, I took the liberty to put something more useful in the LICENSE.txt copyright statement. Check if you're OK with it.

**Comment by SamSaffron** [comment]
This is so awesome! Thanks so much. 

Should we pin to 7.3 instead of 6.9 ?

**Comment by SamSaffron** [comment]
@gschlager  FYI ... :) 🎊

**Comment by ignisf** [comment]
Eh... It won't have any consequences I think. I won't be releasing an older version of V8 anyway so it's effectively pinning it to 7.3 even now

**Comment by gschlager** [comment]
Thanks! Unfortunately my regular expression still doesn't work. I did a little bit of digging in the code from V8 and libv8 and I think I figured out the reason. I created an issue for it. https://github.com/cowboyd/libv8/issues/278

**Pull request merged**
